nop:
  debug: true


  server:
    port: 9092

  rpc:
    proxy:
      allowed-service-names: '*'

  cluster:
    registration:
      enabled: true

    sentinel:
      flow-rules: |
        [{
          resource: "/graphql",
          grade: 1,
          count: 3
        }]

  auth:
    login:
      allow-create-default-user: true # 如果用户表为空，则自动创建缺省账户nop, 密码123
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:./db/test
    username: sa
    password:

  orm:
    init-database-schema: true

  graphql:
    schema-introspection:
      enabled: true

quarkus:
  http:
    host: 0.0.0.0
    port: ${nop.server.port}

  log:
    level: INFO
    category:
      "com.alibaba.nacos":
        level: INFO