nop:
  debug: true
  orm:
    init-database-schema: true

  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:./db/demo
    username: sa
    password:



management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    prometheus:
      enabled: true