name: Sync Docs to Nop Community

on:
  push:
    branches:
      - master
    paths:
      - docs/**
  workflow_dispatch:
  
jobs:
  sync-docs-to-community:
    uses: nop-platform/.github/.github/workflows/sync-project-docs.yml@main
    with:
      repo: nop-entropy-docs
    secrets:
      token: ${{ secrets.NOP_PROJECT_DOCS_PAT }}
